name: 🐞 Bug report
description: Report an issue with Aurelia-Slickgrid
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a way to reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) would be nice unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: You can optionally tell us what is your expectation from the lib?
      placeholder: Expectation
    validations:
      required: false
  - type: textarea
    id: system-info
    attributes:
      label: Environment Info
      description: output of `npx envinfo --system --npmPackages 'aurelia-slickgrid' --binaries --browsers`
      render: shell
      placeholder: |
        System
        Browsers
        Aurelia (x.y)
        Aurelia-Slickgrid (x.y)
        TypeScript (x.y)
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [HOWTO - Quick Start](https://ghiscoding.gitbook.io/aurelia-slickgrid/getting-started/quick-start).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/ghiscoding/aurelia-slickgrid/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/aurelia-slickgrid/discussions).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
